#!/bin/bash
set -o nounset
set -o errexit

# Based on https://wiki.ubuntuusers.de/Skripte/Backup_mit_RSYNC#Beispiel-Minimal-Variante

if [[ "$#" -ne 1 ]]; then
	echo "Usage: $(basename "$0") /path/to/backup/dir"
	exit 1
fi

TARGET=$1

if [[ ! -d $TARGET ]]; then
	echo "$TARGET is not a directory!"
	exit 1
fi

SOURCE=~
TODAY=$(date +%Y-%m-%d)

rsync --archive --relative --progress --delete \
	--delete-excluded \
	--exclude-from=backup-exclude.txt \
	"${SOURCE}"  "${TARGET}/backup-$(hostname)-${TODAY}/" --link-dest="${TARGET}/backup-$(hostname)-latest/"

ln -nsf "${TARGET}/backup-$(hostname)-${TODAY}/" "${TARGET}/backup-$(hostname)-latest"
