#!/bin/bash
set -o nounset
set -o errexit

# Based on https://wiki.ubuntuusers.de/Skripte/Backup_mit_RSYNC#Beispiel-Minimal-Variante
# Trying to follow practices described in https://jmmv.dev/series.html#Shell%20readability

readonly SCRIPT_NAME="${0##*/}"
readonly SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

perform_backup() {
	local SOURCE="${1}"; shift
	local TARGET="${1}"; shift
	local TODAY="${1}"; shift

	echo rsync --archive --relative --progress --delete \
		--delete-excluded \
		--exclude-from=backup-exclude.txt \
		"${SOURCE}"  "${TARGET}/backup-$(hostname)-${TODAY}/" --link-dest="${TARGET}/backup-$(hostname)-latest/"

	echo ln -nsf "${TARGET}/backup-$(hostname)-${TODAY}/" "${TARGET}/backup-$(hostname)-latest"
}

main() {
	if [[ "$#" -ne 1 ]]; then
		echo "Usage: $SCRIPT_NAME /path/to/backup/dir"
		exit 1
	fi

	local TARGET="${1}"; shift

	if [[ ! -d $TARGET ]]; then
		echo "$TARGET is not a directory!"
		exit 1
	fi

	local SOURCE=~
	local TODAY=$(date +%Y-%m-%d)

	perform_backup "$SOURCE" "$TARGET" "$TODAY"
}

main "${@}"
